#!/bin/bash
set -e # stop if it fails at any point

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="bootstrap"Í
printf "${CYAN} ====== ${LABEL} ======${NO_COLOR}\n"

ABS_PATH=$(readlink -f "$0")
PROJECT_PATH=$(dirname $ABS_PATH)

python "$PROJECT_PATH/ECS/ecs.py" "-a 0.0.0.0" "-p 40823" "-ll FINEST"

